### ISSUE TITLE
No more than ≃20k videos 

### ISSUE THREAD

**Issue by ghadbanoa** [jolantahuba/YT-Backup#3]
Hello there,

First of all, thanks for the great help.
However, it doesn't support backing up more than 20k videos.
Could you help/ update with that?

Thanks in advance!

Best regards,

**Comment by jolantahuba** [comment]
Hi!
One playlist can store up to 5000 videos, and I have just tried to export a playlist with about 4.2k videos.
It worked fine, so I believe it is not a problem with amount of videos in one playlist.
But...
Since YouTube API has daily limitation for the maximum number of free requests, and this app is using only them,
it might be caused by exceeding these limits.
You can try to export for example 5 playlists one day, then another 5 next day.
Thank you!

PS That's a great collection of videos! :)
