### ISSUE TITLE
Export date added to playlist

### ISSUE THREAD

**Issue by nattanyz** [jolantahuba/YT-Backup#4]
Hello! Thanks for building this wonderful little app, it's greatly appreciated :D Have been slowly clearing out my Watch Later since I hit 5000 videos a while back and having a backup of my list as a cold hard CSV file has been so reassuring. 

I know this won't be applicable to Watch Later since that's private, but would it be possible to include the date each video was added to the playlist as part of the export? :)

P.S. I don't want to trouble you with another issue, but another feature I'd personally love to see is the ability to export the thumbnails (or the links to them)!

**Comment by jolantahuba** [comment]
Hi,
Thank you very much for the suggestions! And yes, I trust the hard files more than any website too :)

I think it is actually a good idea to add these information to the export file - so I did it.
Now the backup file includes also:
- the date that video was added to the playlist
- link to the video image (480x360)

Unfortunately, if the video would be deleted - you won't be able to see the video image. That's because it's just a link to the thumbnail somewhere on the YouTube servers - I can't do much about it (at least for now).

If you really care, however, there are some ways to find the information about deleted videos. You can for example:
- check the ID of the deleted video in search engine (Google, Yahoo)
- use https://archive.org/web/

I hope it helps, and wish you best with clearing your Watch Later list!

**Comment by nattanyz** [comment]
Yay, thanks so much for your great work and the prompt update! Excited to get to backing up all my playlists now. :) I know there’s a way to keep track of playlists and identify deleted videos (https://www.recovermy.video/), but sadly it can’t find this info retroactively.
Keep doing what you do! You’ve inspired me, maybe one day I’ll pursue building something more custom to keep track of my videos :D 💯
